name: Setup Python Deps
description: Install Python 3.12 and Poetry Dependencies
runs:
  using: composite
  steps:
    - name: Install Poetry
      run: pipx install poetry
      shell: bash
    - name: Setup Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'poetry'
    - name: Display Python Version
      run: python --version
      shell: bash
    - name: Install Dependencies
      run: poetry install
      shell: bash
