name: Docker Image Builds
on:
  workflow_dispatch:
  pull_request:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build-dev:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Development Image
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile.dev
          context: .
          platforms: linux/arm64,linux/amd64
          tags: glossawy/rss-feed-editor:dev
          cache-from: type=gha
          cache-to: type=gha,mode=max
  build-backend:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Backend Image
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile
          context: .
          platforms: linux/arm64,linux/amd64
          tags: glossawy/rss-feed-editor:verify
          cache-from: type=gha
          cache-to: type=gha,mode=max
  build-frontend:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Frontend Image
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile.frontend
          context: .
          platforms: linux/arm64,linux/amd64
          tags: glossawy/rss-feed-editor-frontend:verify
          cache-from: type=gha
          cache-to: type=gha,mode=max
