name: 'Python Checks'
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
  pull-requests: read
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  lint-python:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup-python-deps
      - name: Run Pylint
        run: poetry run pylint ./app
      - name: Run isort
        run: poetry run isort ./app
      - name: Run flake8
        run: poetry run flake8 ./app
