name: Publish Docker Images

on:
  push:
    branches:
      - main
  release:
    types:
      - published

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  push_backend:
    name: Push Backend Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Gather Tags and Labels (Release)
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: glossawy/rss-feed-editor
          tags: type=match,pattern=\d.\d,group=0
        if: ${{ github.event_name == 'release' }}

      - name: Gather Tags and Labels (Push)
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: glossawy/rss-feed-editor
          tags: type=raw,value=edge
        if: ${{ github.event_name == 'push' }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile
          context: .
          platforms: linux/arm64,linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  push_frontend:
    name: Push Frontend Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Gather Tags and Labels (Release)
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: glossawy/rss-feed-editor-frontend
          tags: type=match,pattern=\d.\d,group=0
        if: ${{ github.event_name == 'release' }}

      - name: Gather Tags and Labels (Push)
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: glossawy/rss-feed-editor-frontend
          tags: type=raw,value=edge
        if: ${{ github.event_name == 'push' }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile.frontend
          context: .
          platforms: linux/arm64,linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
